# Site settings
name: Less Or More
email: yanglihaut2013@126.com
author: Clover
url: https://github.com/cloverapp1
resume_site: https://github.com/cloverapp1
github: https://github.com/cloverapp1
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: Clover
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Clover

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

